# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  #change_app_package_name: ^1.1.0
  csv: ^6.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  get: ^4.6.5
  http: ^1.2.1
  lottie: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/